<?php
$title = 'Nowy Widoczek Produktu';
$this->headTitle($title);

?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<div class="form-group">
    <?php
    $form->setAttribute('action', $this->url('views', array('action' => 'add')));
    $form->get('submit')->setValue('Zapisz');
    $form->prepare();

    echo $this->form()->openTag($form);
    echo $this->formHidden($form->get('id'));

    echo $this->formRow($form->get('view_name'));

    echo $this->formRow($form->get('view_active'));

    echo $this->formRow($form->get('view_type'));

    echo $this->formRow($form->get('view_domains'));

    echo $this->formSubmit($form->get('submit'));
    echo $this->form()->closeTag();
    ?>
</div>
