<div class="row">
	
	
    <?php if (isset($products)){ ?>
        <table id="table_id" class="table table-striped table-bordered table-hover dataTable no-footer"> 
		    <thead>
		        <tr>
		            <th>Id</th>
		            <th>Nazwa</th>
		            
		            <th>Edytuj / Usuń</th>
		        </tr>
		    </thead>
		    <tbody>
		    	 <?php foreach($products as $key => $product): ?>
		         <tr>
		            <td><?php echo $key ?></td>
		            <td><?php echo $product['name']; ?></td>
		            
		            <td>
		                <a href="<?php echo $this->url('product', array('action'=>'edit', 'id' => $key));?>"><i class="btn btn-warning btn-circle fa fa-pencil fa-fw"></i></a>
		                <a href="<?php echo $this->url('product', array('action'=>'delete', 'id' => $key));?>"><i class="btn btn-danger btn-circle fa fa-ban fa-fw"></i></a>
		            </td>
		        </tr>
		        <?php endforeach; ?>
		    </tbody>
		</table>
    <?php }else{ ?>
    	Brak wyników do wyświetlenia
    	<?php } ?>
</div>



<script type="text/javascript">
	$(document).ready(function(){
    	$('#table_id').DataTable({
    		"aoColumnDefs": [
		        { 
		          "bSortable": false, 
		          "aTargets": [ -1 ] // <-- gets last column and turns off sorting
		         } 
		     ]
    	});
	});
</script>
