Application\Entity\ProductsAttributes:
    type: entity
    table: products_attributes
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        attributeValue:
            type: string
            nullable: true
            length: 256
            fixed: false
            comment: ''
            column: attribute_value
    manyToOne:
        views:
            targetEntity: Application\Entity\Views
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                view_id:
                    referencedColumnName: id
            orphanRemoval: false
        products:
            targetEntity: Application\Entity\Products
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                products_id:
                    referencedColumnName: id
            orphanRemoval: false
        attributes:
            targetEntity: Application\Entity\Attributes
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                attributes_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
