Application\Entity\Views:
    type: entity
    table: views
    indexes:
        IDX_12F09C87E361C6CF:
            columns:
                - id_products_type
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
        isActive:
            type: boolean
            nullable: true
            comment: ''
            column: is_active
        type:
            type: integer
            nullable: true
            comment: ''
            column: type
    manyToOne:
        idProductType:
            targetEntity: Application\Entity\ProductTypes
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_products_type:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
