Application\Entity\ProductsCategories:
    type: entity
    table: products_categories
    indexes:
        IDX_E3C5666EBAAF4009:
            columns:
                - category_id
        IDX_E3C5666E6C8A81A9:
            columns:
                - products_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    manyToOne:
        domains:
            targetEntity: Application\Entity\Domains
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                domains_id:
                    referencedColumnName: id
            orphanRemoval: false
        products:
            targetEntity: Application\Entity\Products
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                products_id:
                    referencedColumnName: id
            orphanRemoval: false
        categories:
            targetEntity: Application\Entity\Categories
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                category_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
