Application\Entity\ViewsDomains:
    type: entity
    table: views_domains
    indexes:
        IDX_12F09D873700F4DC:
            columns:
                - id_domains
        FK_E3C4666EE272FF2E:
            columns:
                - id_view
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: id
            generator:
                strategy: IDENTITY
    fields:
        isDefault:
            type: boolean
            nullable: true
            comment: ''
            column: is_default
    manyToOne:
        idDomains:
            targetEntity: Application\Entity\Domains
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_domains:
                    referencedColumnName: id
            orphanRemoval: false
        idViews:
            targetEntity: Application\Entity\Views
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_view:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
