Application\Entity\Attributes:
    type: entity
    table: attributes
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: true
            length: 45
            fixed: false
            comment: ''
        description:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
        type:
            type: integer
            nullable: true
            comment: ''
    lifecycleCallbacks: {  }
