<?php

$title = 'Dodawanie nowej Domeny';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<div class="form-group">
<?php
	$form->setAttribute('action', $this->url('domains', array('action' => 'add')));
	$form->get('submit')->setValue('Zapisz');
	$form->prepare();

	echo $this->form()->openTag($form);
	echo $this->formHidden($form->get('id'));
	echo $this->formRow($form->get('name'));
	echo $this->formRow($form->get('url'));
	echo $this->formRow($form->get('is_active'));
	echo $this->formSubmit($form->get('submit'));
	echo $this->form()->closeTag();
	
?>

</div>