<div class="row">
<div class="action_buttons">
	<a class="" href="<?php echo $this->url('domains', array('action'=>'add'));?>"><i class="btn btn-success btn-circle fa fa-plus-square fa-fw"></i> Nowa Domena</a>
</div>
<?php if (isset($domains)) : ?>
                <table class="table">
                    <thead>
                    <tr>
                        <th>Id</th>
                        <th>Nazwa</th>
                        <th>Url</th>
                        <th>Aktywna</th>
                        <th></th>
                    </tr>
                    </thead>
                <?php foreach($domains as $domain): ?>
                	<?php 
                		$domain->getIsActive() ? $activity = 'active' : $activity = 'none_active';
                	?>
                    <tbody>
                    <tr>
                        <td><?php echo $domain->getId(); ?></td>
                        <td><?php echo $domain->getName(); ?></td>
                        <td><?php  echo $domain->getUrl();  ?></td>
                        <td class="<?php echo $activity; ?>"><span></span></td>
                        <td>
                            <a href="<?php echo $this->url('domains', array('action'=>'edit', 'id' => $domain->getId()));?>"><i class="btn btn-warning btn-circle fa fa-pencil fa-fw"></i></a>
                            <a class="remove_button" href="<?php echo $this->url('domains', array('action'=>'delete', 'id' => $domain->getId()));?>"><i class="btn btn-danger btn-circle fa fa-ban fa-fw"></i></a>
                        </td>
                    </tr>
                    </tbody>
                <?php endforeach; ?>
                </table>
                <?php endif; ?>
</div>
<script type="text/javascript">
	$(document).ready(function(){
		/**
	 * Usunięcie domeny
	 * */
		
		$( '.table' ).on("click", ".remove_button", function(e) {
			e.preventDefault();
			var result = confirm("Napewno chcesz usunąć tą domenę");
			if (result==true) {
			    window.location = $(this).attr('href');
			}
			
		});
	});
	
</script>
