<?php
	$title = 'Nowy typ Produktu';
	$this->headTitle($title);

?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<div class="form-group">
<?php
	$form->setAttribute('action', $this->url('products-type', array('action' => 'add')));
	$form->get('submit')->setValue('Zapisz');
	$form->prepare();

	echo $this->form()->openTag($form);
	echo $this->formHidden($form->get('id'));
	
	echo $this->formRow($form->get('name'));
	
	echo $this->formRow($form->get('attributes'));
	
	echo $this->formRow($form->get('domains'));
?>	

<?php require_once 'tree_form.phtml'; ?>	
	
<?php	
	echo $this->formSubmit($form->get('submit'));
	echo $this->form()->closeTag();
?>
</div>































