<?php

$title = 'Add new User';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<div class="form-group">
<?php
	$form->setAttribute('action', $this->url('user', array('action' => 'add')));
	$form->get('submit')->setValue('Dodaj użytkownika');
	$form->prepare();

	echo $this->form()->openTag($form);
	echo $this->formHidden($form->get('id'));
	echo $this->formRow($form->get('user_login'));
	echo $this->formRow($form->get('user_name'));
	echo $this->formRow($form->get('user_lastname'));
	echo $this->formRow($form->get('password'));
	echo $this->formSubmit($form->get('submit'));
	echo $this->form()->closeTag();
?>

</div>