
<div class="row">
<div class="action_buttons">
	<a class="" href="<?php echo $this->url('user', array('action'=>'add'));?>"><i class="btn btn-success btn-circle fa fa-plus-square fa-fw"></i> Nowy Użytkownik</a>
</div>
<?php if (isset($users)) : ?>
                <table class="table">
                    <thead>
                    <tr>
                        <th>Id</th>
                        <th>Login</th>
                        <th>Imie</th>
                        <th>Nazwisko</th>
                        <th></th>
                    </tr>
                    </thead>
                <?php foreach($users as $user): ?>
                    <tbody>
                    <tr>
                        <td><?php echo $user->getId(); ?></td>
                        <td><?php echo $user->getLogin(); ?></td>
                        <td><?php  echo $user->getFirstname();  ?></td>
                        <td><?php echo $user->getLastname(); ?></td>
                        <td>
                            <a href="<?php echo $this->url('user', array('action'=>'edit', 'id' => $user->getId()));?>"><i class="btn btn-warning btn-circle fa fa-pencil fa-fw"></i></a>
                            <a href="<?php echo $this->url('user', array('action'=>'delete', 'id' => $user->getId()));?>"><i class="btn btn-danger btn-circle fa fa-ban fa-fw"></i></a>
                        </td>
                    </tr>
                    </tbody>
                <?php endforeach; ?>
                </table>
                <?php endif; ?>
</div>
